### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ankushKun** [aakashbansal/Songs-Lyrics-Web-Scraper#1]
### I'm getting this error
Going to url :  http://www.song-list.net/edsheeran/songs

---------------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)

<ipython-input-3-ec639f146f80> in <module>()
      5     print("Going to url : ", artist_url)
      6 
----> 7     html_page = urlopen(artist_url)
      8     soup = BeautifulSoup(html_page, 'html.parser')
      9 

5 frames

/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

**Comment by aakashbansal** [comment]
Apologies but I am no longer maintaining this repository. Though, on the first glance it looks as if you have exceeded the maximum hit limit on the link and so you are getting 403 Forbidden as is the case with most scrapping projects. 

Just a pure guess, not sure though. In any case, make sure that you are not overloading the host's servers with too many scrapping requests.

**Comment by ankushKun** [comment]
I'm sure I am not sending too many requests, that error was received on the first try.
Anyways I stumbled across **[pylyrics3](https://pypi.org/project/pylyrics3/)** which is exactly the thing I need.
Thank You

**Comment by aakashbansal** [comment]
Great. 👍
